/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>History</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.History#getActionlist <em>Actionlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getHistory()
 * @model
 * @generated
 */
public interface History extends EObject
{
  /**
   * Returns the value of the '<em><b>Actionlist</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CharacterAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actionlist</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getHistory_Actionlist()
   * @model containment="true"
   * @generated
   */
  EList<CharacterAction> getActionlist();

} // History
