/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.HistoryImpl <em>History</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.HistoryImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHistory()
   * @generated
   */
  int HISTORY = 0;

  /**
   * The feature id for the '<em><b>Actionlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY__ACTIONLIST = 0;

  /**
   * The number of structural features of the '<em>History</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HISTORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CharacterActionImpl <em>Character Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CharacterActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCharacterAction()
   * @generated
   */
  int CHARACTER_ACTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_ACTION__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Character Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionsImpl <em>Actions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ActionsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getActions()
   * @generated
   */
  int ACTIONS = 2;

  /**
   * The number of structural features of the '<em>Actions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RestImpl <em>Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RestImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRest()
   * @generated
   */
  int REST = 3;

  /**
   * The number of structural features of the '<em>Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LongRestImpl <em>Long Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LongRestImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLongRest()
   * @generated
   */
  int LONG_REST = 4;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_REST__LEVEL = REST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Long Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_REST_FEATURE_COUNT = REST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ShortRestImpl <em>Short Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ShortRestImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShortRest()
   * @generated
   */
  int SHORT_REST = 5;

  /**
   * The feature id for the '<em><b>Healing</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHORT_REST__HEALING = REST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Short Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHORT_REST_FEATURE_COUNT = REST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SpellImpl <em>Spell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SpellImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSpell()
   * @generated
   */
  int SPELL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL__NAME = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL__LEVEL = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Spell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPELL_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AttackImpl <em>Attack</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AttackImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAttack()
   * @generated
   */
  int ATTACK = 7;

  /**
   * The feature id for the '<em><b>Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTACK__DAMAGE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Attack</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTACK_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MoveImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMove()
   * @generated
   */
  int MOVE = 8;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DISTANCE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.History <em>History</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>History</em>'.
   * @see org.xtext.example.mydsl.myDsl.History
   * @generated
   */
  EClass getHistory();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.History#getActionlist <em>Actionlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actionlist</em>'.
   * @see org.xtext.example.mydsl.myDsl.History#getActionlist()
   * @see #getHistory()
   * @generated
   */
  EReference getHistory_Actionlist();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CharacterAction <em>Character Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Character Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.CharacterAction
   * @generated
   */
  EClass getCharacterAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CharacterAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.CharacterAction#getName()
   * @see #getCharacterAction()
   * @generated
   */
  EAttribute getCharacterAction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.CharacterAction#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.CharacterAction#getActions()
   * @see #getCharacterAction()
   * @generated
   */
  EReference getCharacterAction_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Actions
   * @generated
   */
  EClass getActions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rest
   * @generated
   */
  EClass getRest();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.LongRest <em>Long Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Long Rest</em>'.
   * @see org.xtext.example.mydsl.myDsl.LongRest
   * @generated
   */
  EClass getLongRest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.LongRest#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.LongRest#getLevel()
   * @see #getLongRest()
   * @generated
   */
  EAttribute getLongRest_Level();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ShortRest <em>Short Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Short Rest</em>'.
   * @see org.xtext.example.mydsl.myDsl.ShortRest
   * @generated
   */
  EClass getShortRest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ShortRest#getHealing <em>Healing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Healing</em>'.
   * @see org.xtext.example.mydsl.myDsl.ShortRest#getHealing()
   * @see #getShortRest()
   * @generated
   */
  EAttribute getShortRest_Healing();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Spell <em>Spell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spell</em>'.
   * @see org.xtext.example.mydsl.myDsl.Spell
   * @generated
   */
  EClass getSpell();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Spell#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Spell#getName()
   * @see #getSpell()
   * @generated
   */
  EAttribute getSpell_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Spell#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.Spell#getLevel()
   * @see #getSpell()
   * @generated
   */
  EAttribute getSpell_Level();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Attack <em>Attack</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attack</em>'.
   * @see org.xtext.example.mydsl.myDsl.Attack
   * @generated
   */
  EClass getAttack();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Attack#getDamage <em>Damage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Damage</em>'.
   * @see org.xtext.example.mydsl.myDsl.Attack#getDamage()
   * @see #getAttack()
   * @generated
   */
  EAttribute getAttack_Damage();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see org.xtext.example.mydsl.myDsl.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Move#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see org.xtext.example.mydsl.myDsl.Move#getDistance()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Distance();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.HistoryImpl <em>History</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.HistoryImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getHistory()
     * @generated
     */
    EClass HISTORY = eINSTANCE.getHistory();

    /**
     * The meta object literal for the '<em><b>Actionlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HISTORY__ACTIONLIST = eINSTANCE.getHistory_Actionlist();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CharacterActionImpl <em>Character Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CharacterActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCharacterAction()
     * @generated
     */
    EClass CHARACTER_ACTION = eINSTANCE.getCharacterAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER_ACTION__NAME = eINSTANCE.getCharacterAction_Name();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHARACTER_ACTION__ACTIONS = eINSTANCE.getCharacterAction_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ActionsImpl <em>Actions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ActionsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getActions()
     * @generated
     */
    EClass ACTIONS = eINSTANCE.getActions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RestImpl <em>Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RestImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRest()
     * @generated
     */
    EClass REST = eINSTANCE.getRest();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LongRestImpl <em>Long Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LongRestImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLongRest()
     * @generated
     */
    EClass LONG_REST = eINSTANCE.getLongRest();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LONG_REST__LEVEL = eINSTANCE.getLongRest_Level();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ShortRestImpl <em>Short Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ShortRestImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShortRest()
     * @generated
     */
    EClass SHORT_REST = eINSTANCE.getShortRest();

    /**
     * The meta object literal for the '<em><b>Healing</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHORT_REST__HEALING = eINSTANCE.getShortRest_Healing();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SpellImpl <em>Spell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SpellImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSpell()
     * @generated
     */
    EClass SPELL = eINSTANCE.getSpell();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPELL__NAME = eINSTANCE.getSpell_Name();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPELL__LEVEL = eINSTANCE.getSpell_Level();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AttackImpl <em>Attack</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AttackImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAttack()
     * @generated
     */
    EClass ATTACK = eINSTANCE.getAttack();

    /**
     * The meta object literal for the '<em><b>Damage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTACK__DAMAGE = eINSTANCE.getAttack_Damage();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MoveImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__DISTANCE = eINSTANCE.getMove_Distance();

  }

} //MyDslPackage
