/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Short Rest</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ShortRest#getHealing <em>Healing</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getShortRest()
 * @model
 * @generated
 */
public interface ShortRest extends Rest
{
  /**
   * Returns the value of the '<em><b>Healing</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Healing</em>' attribute.
   * @see #setHealing(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getShortRest_Healing()
   * @model
   * @generated
   */
  int getHealing();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ShortRest#getHealing <em>Healing</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Healing</em>' attribute.
   * @see #getHealing()
   * @generated
   */
  void setHealing(int value);

} // ShortRest
